# Generated by Django 2.0.4 on 2018-04-07 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('dance_role', models.CharField(choices=[('F', 'Follow'), ('L', 'Lead')], max_length=10)),
                ('rodo_delaration', models.FileField(upload_to='rodo_directory_path')),
                ('status', models.CharField(default=None, max_length=100)),
                ('status_date', models.CharField(default=None, max_length=100)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
