# Generated by Django 2.0.4 on 2018-04-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefon')),
                ('dance_role', models.CharField(choices=[('F', 'Follow'), ('L', 'Lead')], default='Follow', max_length=10, verbose_name='Lead or Follow')),
                ('rodo_delaration', models.FileField(upload_to='rodo_directory_path')),
                ('status', models.CharField(default=None, max_length=100, verbose_name='Status')),
                ('status_date', models.CharField(default=None, max_length=100, verbose_name='Data wysłania')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Grupa')),
            ],
        ),
    ]
